### ISSUE TITLE
Formulaファイルへのversion

### ISSUE THREAD

**Issue by papiron** [unkontributors/homebrew-unko#2]
super_unkoをHomebrewでインストールしようと`brew tap unkontributors/unko`したところ、下記のエラーが発生してtap出来ませんでした。
```
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/unkontributors/homebrew-unko/super_unko.rb
invalid attribute for formula 'unkontributors/unko/super_unko': version (nil)
Error: Cannot tap unkontributors/unko: invalid syntax in tap!
```
Formulaファイルのurlにversion番号が無いため、versionを明示的に指定する必要がありそうです。
super-unkoは複数のコマンドから成り立っており、各コマンド毎にversionが異なります。tagは1.0.5なのですが、これをversionに使って良いか分からず。

**Comment by xztaityozx** [comment]
coreutilsみたいなやつはどういうバージョン付けしてるんでしょう。

**Comment by papiron** [comment]
courutilsのgit logみてみましたが、特定の人がtag付けてるくらいしか分からず。

**Comment by greymd** [comment]
おー、まじですか。前は`version`なくてもいけた気がするんですがね。。
一応、タグは使って良いと思ってます。
大きな変更があったら適宜バージョンを上げよう、という話を以前 @jiro4989 さんとしていました。
https://github.com/unkontributors/super_unko/pull/78

**Comment by greymd** [comment]
`version` を追加したので、tapできるようになりました。

```
$ brew tap unkontributors/unko
Updating Homebrew...
==> Tapping unkontributors/unko
Cloning into '/usr/local/Homebrew/Library/Taps/unkontributors/homebrew-unko'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 10 (delta 1), reused 2 (delta 0), pack-reused 4
Unpacking objects: 100% (10/10), done.
Tapped 1 formula (34 files, 25.9KB).
```

**Comment by greymd** [comment]
一旦closeとします！
